// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9W6lAmIMvTDLjb4fiw3yQv4YZDol9z0A',
    appId: '1:760229073152:web:424b3c06199a439db123e5',
    messagingSenderId: '760229073152',
    projectId: 'sistemagestaofrotas',
    authDomain: 'sistemagestaofrotas.firebaseapp.com',
    storageBucket: 'sistemagestaofrotas.appspot.com',
    measurementId: 'G-W17D6C9RT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3r2dExUR9pEUM3DtWL9lkhlKoQrp7NfY',
    appId: '1:760229073152:android:cdea37a723fe1265b123e5',
    messagingSenderId: '760229073152',
    projectId: 'sistemagestaofrotas',
    storageBucket: 'sistemagestaofrotas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXlcl15hkCfpXYqTSXkCcwUOoGUkHu3f0',
    appId: '1:760229073152:ios:169d99e66b6ede82b123e5',
    messagingSenderId: '760229073152',
    projectId: 'sistemagestaofrotas',
    storageBucket: 'sistemagestaofrotas.appspot.com',
    iosClientId: '760229073152-knl2fjcn2g05b1iosile1jnqtesjm5dt.apps.googleusercontent.com',
    iosBundleId: 'com.example.sistemagestaoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXlcl15hkCfpXYqTSXkCcwUOoGUkHu3f0',
    appId: '1:760229073152:ios:169d99e66b6ede82b123e5',
    messagingSenderId: '760229073152',
    projectId: 'sistemagestaofrotas',
    storageBucket: 'sistemagestaofrotas.appspot.com',
    iosClientId: '760229073152-knl2fjcn2g05b1iosile1jnqtesjm5dt.apps.googleusercontent.com',
    iosBundleId: 'com.example.sistemagestaoApp',
  );
}
